schema_version: 1

context:
  version: "0.2.11"

package:
  name: thrift-ls
  version: ${{ version }}

source:
  url: https://github.com/joyme123/thrift-ls/archive/v${{ version }}.tar.gz
  sha256: dad2e639a66ba6a399562cd28be06981fbd4419d7634312a00f33b6e115d7ce1

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - thrift-ls --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Thrift Language Server
  homepage: https://github.com/joyme123/thrift-ls
  repository: https://github.com/joyme123/thrift-ls

extra:
  recipe-maintainers:
    - danielnachun
