schema_version: 1

context:
  version: "0.2.10"

package:
  name: thrift-ls
  version: ${{ version }}

source:
  url: https://github.com/joyme123/thrift-ls/archive/v${{ version }}.tar.gz
  sha256: fcbbe0a9eff66de2d5fb39cd9719cc7ba7b3c1d6e6cd08a8309f118e4500a27f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - thrift-ls --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Thrift Language Server
  homepage: https://github.com/joyme123/thrift-ls
  repository: https://github.com/joyme123/thrift-ls

extra:
  recipe-maintainers:
    - danielnachun
