schema_version: 1

context:
  version: "0.2.12"

package:
  name: thrift-ls
  version: ${{ version }}

source:
  url: https://github.com/joyme123/thrift-ls/archive/v${{ version }}.tar.gz
  sha256: e32d0c8b8bae241e8a829d88da156124ee5dad12aacfb55a462e868eec07bec0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - thrift-ls --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Thrift Language Server
  homepage: https://github.com/joyme123/thrift-ls
  repository: https://github.com/joyme123/thrift-ls

extra:
  recipe-maintainers:
    - danielnachun
